"""Generate pseudo-OOD "new family" sequences for generalization eval (eval-only).

A pseudo-family is a *per-block recombination* of the MOSFET / IGBT / IC grammar
traits: each process block (prep, oxidation, core cycles, via, metal, backside,
test, ...) is generated by one of the three official families' block generators,
producing a novel-but-rule-consistent process flow. Because we reuse the existing
validated block generators, every emitted step stays inside the known training
vocabulary (no <UNK_STEP>), and every sequence is checked with the organizer
``validate_sequence`` — invalid samples are rejected.

These are for OOD *validation only* and must never enter model training. Output:
    data/eval/pseudo_families/<profile>/raw.csv      # FAMILY,SEQUENCE_ID,STEP
    data/eval/pseudo_families/<profile>/meta.json     # config + accept stats

Usage:
    uv run python scripts/generate_pseudo_families.py --count 5000
    uv run python scripts/generate_pseudo_families.py --count 100 \
        --profiles pseudo_low_power pseudo_power_vertical
"""

from __future__ import annotations

import argparse
import csv
import json
import random
from dataclasses import asdict, dataclass, field
from pathlib import Path

from zero_hack import PROJECT_ROOT
from zero_hack.data.augmented_generator import (
    AugmentationOptions,
    _flag,
    _gen_backside_block,
    _gen_family_prep,
    _gen_final_inspection,
    _gen_first_oxidation,
    _gen_ild_block,
    _gen_initial_measurements,
    _gen_metal_block,
    _gen_passivation_block,
    _gen_pre_process_clean,
    _gen_prefix,
    _gen_suffix,
    _gen_test_suite,
    _gen_via_block,
    _ic_base_cycles,
    _igbt_base_cycles,
    _intermediate_clean,
    _mosfet_base_cycles,
)
from zero_hack.eval.validator import validate_sequence

DEFAULT_OUT_ROOT = PROJECT_ROOT / "data" / "eval" / "pseudo_families"


@dataclass(frozen=True)
class PseudoProfile:
    """A pseudo-family: each block is generated by one base family's grammar.

    ``base_family`` is the closest official family — used later only to choose the
    conditioning ``<FAMILY_*>`` token at eval (never for training).
    """

    name: str
    base_family: str
    prep: str
    oxidation: str
    cycles: str
    via: str
    metal: str
    backside: str
    test: str
    suffix: str
    measurements: str
    options: AugmentationOptions = field(default_factory=AugmentationOptions)


# Three fixed v1 profiles — genuine cross-family trait mixes, not relabelled
# copies. Novelty comes from mixing each BLOCK's base family (prep / cycles /
# via metallurgy / backside / test); the litho-level structure follows each cycle
# family's NATURAL base count so every level-numbered token (ALIGN/EXPOSE/INSPECT/
# MEASURE CD/STRIP LEVEL n) stays inside the training vocabulary (n<=6, via/metal
# at the same levels the official families used). The None-valued option knobs
# stay random per-sequence for combinatorial variety so 5k unique are reachable.
PROFILES: dict[str, PseudoProfile] = {
    # MOSFET epitaxy prep + IC poly-gate cycles + MOSFET (non-tungsten) via +
    # MOSFET backside metallization + MOSFET threshold test. Cycles=ic -> via 3 /
    # metal 4, so a second metal layer (level 5) is in-vocab and left random.
    "pseudo_low_power": PseudoProfile(
        name="pseudo_low_power",
        base_family="mosfet",
        prep="mosfet",
        oxidation="mosfet",
        cycles="ic",
        via="mosfet",
        metal="ic",
        backside="mosfet",
        test="mosfet",
        suffix="mosfet",
        measurements="mosfet",
    ),
    # IGBT prep + dual-implant IGBT cycles (4 levels -> via 5 / metal 6) + MOSFET
    # backside metallization + IGBT breakdown test. Second metal would push to
    # level 7 (OOV), so it is disabled.
    "pseudo_power_vertical": PseudoProfile(
        name="pseudo_power_vertical",
        base_family="igbt",
        prep="igbt",
        oxidation="igbt",
        cycles="igbt",
        via="igbt",
        metal="igbt",
        backside="mosfet",
        test="igbt",
        suffix="igbt",
        measurements="igbt",
        options=AugmentationOptions(second_metal_layer=False),
    ),
    # IC early backside-grind prep + IC cycles + tungsten via fill + IC backside
    # protection, with high measurement density (extra_measurements forced on).
    "pseudo_logic_dense": PseudoProfile(
        name="pseudo_logic_dense",
        base_family="ic",
        prep="ic",
        oxidation="ic",
        cycles="ic",
        via="ic",
        metal="ic",
        backside="ic",
        test="ic",
        suffix="ic",
        measurements="ic",
        options=AugmentationOptions(extra_measurements=True),
    ),
}


def _pseudo_core_cycles(
    rng: random.Random,
    family: str,
    cfg: AugmentationOptions,
) -> tuple[list[str], int]:
    """Base core cycles for ``family`` (no generic extension) + the via litho level.

    We deliberately bypass ``_gen_core_cycles``: its generic extension emits
    level-numbered labels (``INSPECT PATTERN LEVEL 3``, ``MEASURE CD LEVEL 3``,
    ``ALIGN MASK LEVEL 7+``) that are NOT in the training vocabulary. The base
    cycles use only in-vocab labels and land via/metal at the same litho levels
    the official families used (mosfet/ic -> via 3, igbt -> via 5).
    """
    if family == "mosfet":
        return _mosfet_base_cycles(rng, cfg), 3
    if family == "ic":
        return _ic_base_cycles(rng, cfg), 3
    return _igbt_base_cycles(rng, cfg, include_poly_gate_cycle=True), 5


def generate_pseudo_sequence(profile: PseudoProfile, rng: random.Random) -> list[str]:
    """Assemble one sequence, drawing each block from its assigned base family."""
    cfg = profile.options
    steps: list[str] = []
    steps += _gen_prefix(rng)
    steps += _gen_initial_measurements(rng, profile.measurements, cfg)
    steps += _gen_pre_process_clean(rng, profile.prep, cfg)
    steps += _gen_family_prep(rng, profile.prep, cfg)
    steps += _intermediate_clean(rng, cfg)
    steps += _gen_first_oxidation(rng, profile.oxidation, cfg)
    core_steps, via_level = _pseudo_core_cycles(rng, profile.cycles, cfg)
    steps += core_steps
    steps += _intermediate_clean(rng, cfg)
    steps += _gen_ild_block(rng, cfg)
    steps += _gen_via_block(rng, cfg, via_level, profile.via)
    metal_level = via_level + 1
    steps += _gen_metal_block(rng, cfg, metal_level, profile.metal, layer=1)
    if _flag(rng, cfg.second_metal_layer, 0.35):
        steps += _gen_metal_block(rng, cfg, metal_level + 1, profile.metal, layer=2)
    steps += _gen_passivation_block(rng, cfg)
    steps += _gen_backside_block(rng, profile.backside, cfg)
    steps += _gen_final_inspection(rng, profile.measurements, cfg)
    steps += _gen_test_suite(rng, profile.test, cfg)
    steps += _gen_suffix(rng, profile.suffix, cfg)
    return steps


@dataclass
class GenStats:
    requested: int
    attempts: int = 0
    invalid: int = 0
    out_of_vocab: int = 0
    duplicates: int = 0
    accepted: int = 0
    rule_counts: dict[str, int] = field(default_factory=dict)

    @property
    def raw_validity_rate(self) -> float:
        # Fraction of generated (pre-dedup) sequences that pass the validator.
        seen = self.attempts
        return round((seen - self.invalid) / seen, 4) if seen else 0.0


def generate_pseudo_dataset(
    profile: PseudoProfile,
    count: int,
    *,
    vocab: set[str],
    seed: int = 42,
    max_attempts_factor: int = 50,
) -> tuple[list[list[str]], GenStats]:
    rng = random.Random(seed)
    sequences: list[list[str]] = []
    seen: set[tuple[str, ...]] = set()
    stats = GenStats(requested=count)
    max_attempts = max(count * max_attempts_factor, 200)

    while len(sequences) < count and stats.attempts < max_attempts:
        stats.attempts += 1
        seq = generate_pseudo_sequence(profile, rng)
        violations = validate_sequence(seq)
        if violations:
            stats.invalid += 1
            rule = violations[0].rule
            stats.rule_counts[rule] = stats.rule_counts.get(rule, 0) + 1
            continue
        # Closed-vocab safety net: never emit a step the model has no token for.
        if any(step not in vocab for step in seq):
            stats.out_of_vocab += 1
            continue
        key = tuple(seq)
        if key in seen:
            stats.duplicates += 1
            continue
        seen.add(key)
        sequences.append(seq)

    stats.accepted = len(sequences)
    return sequences, stats


def write_pseudo_csv(path: Path, profile_name: str, sequences: list[list[str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["FAMILY", "SEQUENCE_ID", "STEP"])
        for i, seq in enumerate(sequences, start=1):
            seq_id = f"{profile_name}_{i:05d}"
            for step in seq:
                writer.writerow([profile_name, seq_id, step])


def known_vocabulary() -> set[str]:
    """Step inventory of the official families (what the model has in its vocab)."""
    from zero_hack.data import load_sequence_records
    from zero_hack.data.datasets import FAMILY_FILE_NAMES
    from zero_hack.models.common import DEFAULT_SPLITS_DIR

    steps: set[str] = set()
    for family, fname in FAMILY_FILE_NAMES.items():
        stem = fname.removesuffix(".csv")
        for split in ("train", "valid", "test"):
            path = Path(DEFAULT_SPLITS_DIR) / f"{stem}_{split}.csv"
            if path.exists():
                for rec in load_sequence_records(path, family=family):
                    steps.update(rec.steps)
    return steps


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=5000, help="Sequences per profile.")
    parser.add_argument(
        "--profiles",
        nargs="+",
        default=list(PROFILES),
        choices=list(PROFILES),
        help="Which pseudo-family profiles to generate.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out-root", default=str(DEFAULT_OUT_ROOT))
    parser.add_argument(
        "--no-write", action="store_true", help="Validate/report only; do not write CSVs."
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    out_root = Path(args.out_root)
    vocab = known_vocabulary()

    print(f"known training vocabulary: {len(vocab)} steps\n")
    summary: dict[str, dict] = {}

    for name in args.profiles:
        profile = PROFILES[name]
        seqs, stats = generate_pseudo_dataset(profile, args.count, vocab=vocab, seed=args.seed)

        # Independent correctness audit (not just trusting the reject loop).
        revalidated_invalid = sum(1 for s in seqs if validate_sequence(s))
        oov = sorted({step for s in seqs for step in s} - vocab)
        lengths = [len(s) for s in seqs]
        unique = len({tuple(s) for s in seqs})

        ok = revalidated_invalid == 0 and not oov and unique == len(seqs)
        print(f"=== {name} (base={profile.base_family}) ===")
        print(f"  accepted           : {stats.accepted}/{stats.requested}")
        print(f"  raw validity rate  : {stats.raw_validity_rate}  (attempts={stats.attempts})")
        print(f"  re-validated invalid: {revalidated_invalid}")
        print(f"  out-of-vocab steps : {len(oov)} {oov[:5]}")
        print(f"  unique             : {unique}/{len(seqs)}")
        if lengths:
            print(
                f"  length min/mean/max: "
                f"{min(lengths)}/{sum(lengths) // len(lengths)}/{max(lengths)}"
            )
        if stats.rule_counts:
            print(f"  rejected-by-rule   : {stats.rule_counts}")
        print(f"  CORRECT            : {'YES' if ok else 'NO'}\n")

        if not args.no_write:
            prof_dir = out_root / name
            write_pseudo_csv(prof_dir / "raw.csv", name, seqs)
            (prof_dir / "meta.json").write_text(
                json.dumps(
                    {
                        "profile": asdict(profile),
                        "seed": args.seed,
                        "stats": asdict(stats),
                        "raw_validity_rate": stats.raw_validity_rate,
                        "out_of_vocab_steps": oov,
                        "n_sequences": len(seqs),
                        "unique": unique,
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            print(f"  wrote {prof_dir / 'raw.csv'} + meta.json\n")

        summary[name] = {
            "accepted": stats.accepted,
            "raw_validity_rate": stats.raw_validity_rate,
            "revalidated_invalid": revalidated_invalid,
            "out_of_vocab": len(oov),
            "unique": unique,
            "correct": ok,
        }

    print("SUMMARY:", json.dumps(summary, indent=2))
    if not all(v["correct"] for v in summary.values()):
        raise SystemExit("Some profiles failed the correctness audit (see above).")


if __name__ == "__main__":
    main()
